### ISSUE TITLE
Issue with Adding a Feature Image

### ISSUE THREAD

**Issue by mrkrndvs** [pfefferle/autonomie#48] opened 2020-11-14 20:35 UTC
I have been having issues with adding a feature image lately on <a href="https://readwriterespond.com/" rel="noopener noreferrer" target="_blank">Read Write Respond</a>. The system registers the image as it shows up in the social media preview provided by Yoast SEO.

![](https://collect.readwriterespond.com/wp-content/uploads/2020/11/autonomie-feature-image-issue-1024x389.png)

I am assuming that this somehow relates to the theme as I tested out two other themes and they worked with featured images. I also updated to the latest version of Autonomie and am running WordPress 5.5.3

**Comment by pfefferle** [comment] 2020-11-16 08:51
duplicate of #49

**Closed by pfefferle** 2020-11-16 08:51 UTC
